### ISSUE TITLE
 transfer Tokens check Balance

### ISSUE THREAD

**Issue by AleksandrAsimov** [hive-keychain/hive-keychain-extension#82]
When I use transfer Tokens 
![unknown](https://user-images.githubusercontent.com/32066755/102655072-5999cf80-417a-11eb-9742-bfb5ea02b60a.png)
and my balance does not enough to send token, transaction callback info success is true and write into blockchain.

**Comment by 4Ykw** [comment]
I am not 100% sure if the callback checks for these kinds of conditions.

But yeah.. although the write into blockchain will not get processed. UI enhancement? 😉

**Comment by stoodkev** [comment]
Somehow missed that issue.
Yea there's definitely a UI enhancement to be made here.
And as you say, there's no error since it's nothing but a JSON broadcast that is successful.  I'll make sure the confirm button is greyed out if the amount is bigger than balance. 
This is an edge case though, as this is usually already handled by the dApp before sending the request. 

I'll probably fix this after the current refactor is done since it's not urgent.
